import {
  Customer,
  Employee,
  InventoryItem,
  Job,
  Vehicle,
  WorkshopServiceCatalogItem,
} from './types'

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    fullName: 'Vikram Malhotra',
    email: 'vikram.m@autozone.com',
    phone: '+91 98200 41122',
    role: 'ADMIN',
    designation: 'General Manager & Chief Inspector',
    specialization: ['Paint Depth Gauge Analysis', 'Customer Relations', 'Warranty Audit'],
    activeJobCount: 3,
    isActive: true,
  },
  {
    id: 'emp-2',
    fullName: 'Arman Khan',
    email: 'arman.k@autozone.com',
    phone: '+91 98201 55678',
    role: 'MANAGER',
    designation: 'Lead Service Advisor',
    specialization: ['Estimates', 'Client Check-In', 'Quality Assurance'],
    activeJobCount: 4,
    isActive: true,
  },
  {
    id: 'emp-3',
    fullName: 'Rajesh Sharma',
    email: 'rajesh.s@autozone.com',
    phone: '+91 98202 88910',
    role: 'TECHNICIAN',
    designation: 'Master Detailer & Ceramic Specialist',
    specialization: ['Multi-Stage Correction', 'Graphene & Ceramic 9H', 'Rotary Polishing'],
    activeJobCount: 2,
    isActive: true,
  },
  {
    id: 'emp-4',
    fullName: 'Kabir Sengupta',
    email: 'kabir.s@autozone.com',
    phone: '+91 98203 12345',
    role: 'TECHNICIAN',
    designation: 'PPF Master Installer',
    specialization: ['SunTek / XPEL PPF', 'Custom Edge Wrapping', 'Heat Gun Contouring'],
    activeJobCount: 2,
    isActive: true,
  },
  {
    id: 'emp-5',
    fullName: 'Siddharth Rao',
    email: 'siddharth.r@autozone.com',
    phone: '+91 98204 99011',
    role: 'TECHNICIAN',
    designation: 'Interior & Leather Specialist',
    specialization: ['Dry Steam Sanitization', 'Alcantara Restoration', 'Leather Dye Touchup'],
    activeJobCount: 1,
    isActive: true,
  },
  {
    id: 'emp-6',
    fullName: 'Ananya Verma',
    email: 'ananya.v@autozone.com',
    phone: '+91 98205 33445',
    role: 'EMPLOYEE',
    designation: 'Service Advisor & Billing Specialist',
    specialization: ['Job Intake', 'Billing & Tax', 'Customer Handover'],
    activeJobCount: 3,
    isActive: true,
  },
]

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-101',
    fullName: 'Rohan Singhania',
    phone: '+91 98920 11223',
    email: 'rohan.singhania@gmail.com',
    address: 'Flat 14B, Oberoi Sky City, Worli',
    city: 'Mumbai',
    notes: 'VIP Client. Prefers morning deliveries. Owns multiple supercars.',
    totalVisits: 5,
    totalSpent: 385000,
    outstandingBalance: 0,
    createdAt: '2025-04-12T10:00:00Z',
    updatedAt: '2026-09-24T14:30:00Z',
  },
  {
    id: 'cust-102',
    fullName: 'Dr. Priya Nambiar',
    phone: '+91 98710 44556',
    email: 'priya.nambiar@apollohospitals.org',
    address: 'Bungalow 7, Juhu Tara Road',
    city: 'Mumbai',
    notes: 'Allergic to strong chemical perfumes. Use fragrance-free interior cleaners only.',
    totalVisits: 3,
    totalSpent: 142000,
    outstandingBalance: 15000,
    createdAt: '2025-08-19T09:15:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'cust-103',
    fullName: 'Zubair Merchant',
    phone: '+91 98199 77889',
    email: 'z.merchant@merchantgroup.in',
    address: 'Penthouse 32, Lodha Bellissimo, Mahalaxmi',
    city: 'Mumbai',
    notes: 'Strict about panel edges and zero swirl marks under inspection lamps.',
    totalVisits: 8,
    totalSpent: 620000,
    outstandingBalance: 0,
    createdAt: '2024-11-05T14:20:00Z',
    updatedAt: '2026-09-26T08:45:00Z',
  },
  {
    id: 'cust-104',
    fullName: 'Aditya Kashyap',
    phone: '+91 99200 66332',
    email: 'aditya.kashyap@fintechventures.io',
    address: 'Tower 4, Hiranandani Gardens, Powai',
    city: 'Mumbai',
    notes: 'First-time customer. Referred by Rohan Singhania.',
    totalVisits: 1,
    totalSpent: 45000,
    outstandingBalance: 0,
    createdAt: '2026-09-20T11:00:00Z',
    updatedAt: '2026-09-20T11:00:00Z',
  },
  {
    id: 'cust-105',
    fullName: 'Kavita Chawla',
    phone: '+91 98211 99443',
    email: 'kavita@chawladesigns.com',
    address: '12 Pali Hill, Bandra West',
    city: 'Mumbai',
    notes: 'Requires detailed before/after photo report with every invoice.',
    totalVisits: 4,
    totalSpent: 210000,
    outstandingBalance: 32000,
    createdAt: '2025-06-10T16:00:00Z',
    updatedAt: '2026-09-25T17:15:00Z',
  },
]

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    customerId: 'cust-101',
    registrationNumber: 'MH 01 DX 0911',
    make: 'Porsche',
    model: '911 GT3 (992)',
    variant: 'Clubsport Package, Carbon Roof',
    year: 2024,
    color: 'Shark Blue',
    fuelType: 'PETROL',
    transmission: 'DUAL_CLUTCH',
    vin: 'WP0ZZZ99ZPS182931',
    currentOdometer: 6420,
    bodyType: 'SUPERCAR',
    notes: 'Carbon ceramic brakes installed. Clean calipers with pH-neutral wheel cleaner only.',
    createdAt: '2025-04-12T10:10:00Z',
  },
  {
    id: 'veh-2',
    customerId: 'cust-101',
    registrationNumber: 'MH 02 FM 7700',
    make: 'Mercedes-AMG',
    model: 'G 63',
    variant: 'Night Package V8 Biturbo',
    year: 2023,
    color: 'Obsidian Black Metallic',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    vin: 'W1N4632761X492019',
    currentOdometer: 18900,
    bodyType: 'SUV',
    notes: 'Matte running boards and carbon trim exterior.',
    createdAt: '2025-09-15T12:00:00Z',
  },
  {
    id: 'veh-3',
    customerId: 'cust-102',
    registrationNumber: 'MH 02 EQ 4500',
    make: 'BMW',
    model: 'M4 Competition',
    variant: 'M xDrive Coupé',
    year: 2023,
    color: 'Isle of Man Green Metallic',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    vin: 'WBA33AY05PFP39012',
    currentOdometer: 14250,
    bodyType: 'COUPE',
    notes: 'M Carbon bucket seats with Silverstone leather.',
    createdAt: '2025-08-19T09:30:00Z',
  },
  {
    id: 'veh-4',
    customerId: 'cust-103',
    registrationNumber: 'MH 01 EN 0007',
    make: 'Audi',
    model: 'RS 6 Avant',
    variant: 'Dynamic Package Plus',
    year: 2024,
    color: 'Nardo Grey',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    vin: 'WAUZZZF28RA091234',
    currentOdometer: 9100,
    bodyType: 'SEDAN',
    notes: 'Gloss black optical package, full alcantara roof lining.',
    createdAt: '2024-11-05T14:35:00Z',
  },
  {
    id: 'veh-5',
    customerId: 'cust-104',
    registrationNumber: 'MH 04 KB 9922',
    make: 'Land Rover',
    model: 'Defender 110',
    variant: 'P400 X-Dynamic HSE',
    year: 2023,
    color: 'Carpathian Grey with Satin Film',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    vin: 'SALWA2V42PA876120',
    currentOdometer: 23400,
    bodyType: 'SUV',
    notes: 'Off-road underbody mud accumulation. Needs deep chassis steam cleaning.',
    createdAt: '2026-09-20T11:15:00Z',
  },
  {
    id: 'veh-6',
    customerId: 'cust-105',
    registrationNumber: 'MH 02 FG 3311',
    make: 'Tesla',
    model: 'Model S Plaid',
    variant: 'Tri-Motor AWD',
    year: 2024,
    color: 'Ultra Red',
    fuelType: 'ELECTRIC',
    transmission: 'AUTOMATIC',
    vin: '5YJSA1E63PF829101',
    currentOdometer: 4800,
    bodyType: 'SEDAN',
    notes: 'High voltage caution. Keep away from charging port high-pressure spray.',
    createdAt: '2025-06-10T16:20:00Z',
  },
]

export const SERVICE_CATALOG: WorkshopServiceCatalogItem[] = [
  {
    id: 'srv-ppf-full',
    title: 'Self-Healing TPU Paint Protection Film (Full Body)',
    category: 'PPF',
    description: '10-year warranty 8.5mil hydrophobic thermoplastic polyurethane wrap with precision CAD computer-cut patterns and wrapped edges.',
    basePrice: 185000,
    defaultDurationHours: 36,
    recommendedMaterials: ['SunTek Ultra PPF Roll', 'XPEL Installation Gel', 'IPA Surface Prep'],
  },
  {
    id: 'srv-ppf-front',
    title: 'High-Impact Track Pack PPF (Front Bumper, Hood, Fenders, Mirrors)',
    category: 'PPF',
    description: 'Targeted heavy-impact zone protection against stone chips, highway grit, and bug acid etching.',
    basePrice: 65000,
    defaultDurationHours: 16,
    recommendedMaterials: ['SunTek Ultra PPF Roll', 'XPEL Installation Gel'],
  },
  {
    id: 'srv-ceramic-9h',
    title: '9H Dual-Layer Matrix Ceramic Coating (5-Year Warranty)',
    category: 'CERAMIC',
    description: 'Base coat 9H hardness layer followed by ultra-hydrophobic fluoropolymer topcoat for extreme gloss and 110° water contact angle.',
    basePrice: 42000,
    defaultDurationHours: 18,
    recommendedMaterials: ['Gyeon Q2 Syncro EVO', 'Gyeon Prep Alcohol Spray', 'Gyeon Q2M Cure'],
  },
  {
    id: 'srv-paint-correction-3stage',
    title: 'Multi-Stage Concours Paint Correction & Swirl Removal',
    category: 'PAINT_CORRECTION',
    description: 'Step 1 Heavy Cut rotary compound, Step 2 Dual-Action medium polish, Step 3 Ultra-Fine jeweling polish for 95%+ swirl defect removal.',
    basePrice: 22000,
    defaultDurationHours: 14,
    recommendedMaterials: ['Koch-Chemie Heavy Cut H9.02', 'Koch-Chemie Micro Cut M3.02', 'Rupes Yellow Foam Pad'],
  },
  {
    id: 'srv-interior-steam-spa',
    title: 'Deep Interior Steam Sanitization & Leather Hydration',
    category: 'INTERIOR',
    description: '170°C dry steam extraction for carpets and headliner, pH-neutral enzymatic leather cleaning, matte UV-blocker balm application.',
    basePrice: 12500,
    defaultDurationHours: 8,
    recommendedMaterials: ['Koch-Chemie Pol Star', 'Koch-Chemie Leather Star', 'Detailing Horsehair Brushes'],
  },
  {
    id: 'srv-wheels-off-ceramic',
    title: 'Wheels-Off Ceramic Coating & Brake Caliper Sealant',
    category: 'WHEELS',
    description: 'Wheel removal, wheel barrel acid-free de-ironing, heat-resistant 1200°C ceramic coating on calipers and barrels.',
    basePrice: 16000,
    defaultDurationHours: 6,
    recommendedMaterials: ['Gyeon Q2 Rim Ceramic', 'Bilt Hamber Auto-Wheel Decon'],
  },
  {
    id: 'srv-glass-ceramic',
    title: 'Windshield & All-Glass Hydrophobic Ceramic Rain Repellent',
    category: 'CERAMIC',
    description: 'Cerium oxide glass polish decontamination followed by silane-based water repellent for 100km/h wiperless rain clearance.',
    basePrice: 7500,
    defaultDurationHours: 3,
    recommendedMaterials: ['Gyeon Q2 View Glass Kit', 'Cerium Oxide Glass Polish'],
  },
  {
    id: 'srv-engine-bay-detail',
    title: 'Engine Bay Steam Cleaning & Satin Dressing',
    category: 'DETAILING',
    description: 'Sensitive electronics taping, steam degreasing, safe moisture purge, and non-greasy anti-static polymer dressing.',
    basePrice: 6500,
    defaultDurationHours: 4,
    recommendedMaterials: ['Koch-Chemie Motorplast', 'Bilt Hamber Surfex HD'],
  },
]

export const INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Gyeon Q2 Syncro EVO Ceramic Coating (50ml Kit)',
    sku: 'GY-SYNCRO-50',
    category: 'COATING',
    unit: 'Kit',
    unitCost: 8200,
    stockQuantity: 14,
    minimumThreshold: 4,
    supplier: 'Gyeon Quartz Global / Detailers India',
  },
  {
    id: 'inv-2',
    name: 'SunTek Ultra 60" Gloss TPU PPF Roll (50 Feet)',
    sku: 'ST-PPF-60GL',
    category: 'PPF',
    unit: 'Roll',
    unitCost: 68000,
    stockQuantity: 5,
    minimumThreshold: 2,
    supplier: 'Eastman Chemical Company',
  },
  {
    id: 'inv-3',
    name: 'Koch-Chemie Heavy Cut H9.02 (1 Liter)',
    sku: 'KC-H902-1L',
    category: 'POLISH',
    unit: 'Bottle',
    unitCost: 2400,
    stockQuantity: 18,
    minimumThreshold: 5,
    supplier: 'Koch-Chemie GmbH',
  },
  {
    id: 'inv-4',
    name: 'Koch-Chemie Micro Cut M3.02 Jeweling Polish (1 Liter)',
    sku: 'KC-M302-1L',
    category: 'POLISH',
    unit: 'Bottle',
    unitCost: 2600,
    stockQuantity: 12,
    minimumThreshold: 4,
    supplier: 'Koch-Chemie GmbH',
  },
  {
    id: 'inv-5',
    name: 'Gyeon Q2 Rim High-Temp Wheel Coating (30ml)',
    sku: 'GY-RIM-30',
    category: 'COATING',
    unit: 'Bottle',
    unitCost: 3100,
    stockQuantity: 9,
    minimumThreshold: 3,
    supplier: 'Gyeon Quartz Global',
  },
  {
    id: 'inv-6',
    name: 'Koch-Chemie Leather Star Conditioner (1 Liter)',
    sku: 'KC-LS-1L',
    category: 'CLEANER',
    unit: 'Bottle',
    unitCost: 1950,
    stockQuantity: 11,
    minimumThreshold: 3,
    supplier: 'Koch-Chemie GmbH',
  },
  {
    id: 'inv-7',
    name: 'Edgeless Korean 500GSM Microfiber Pack (10 Pcs)',
    sku: 'MF-EDG-500',
    category: 'CONSUMABLE',
    unit: 'Pack',
    unitCost: 1400,
    stockQuantity: 35,
    minimumThreshold: 10,
    supplier: 'Autofiber Korea',
  },
]

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-101',
    jobCode: 'AZ-101',
    customerId: 'cust-101',
    vehicleId: 'veh-1',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    assignedEmployeeId: 'emp-2',
    assignedTechnicianIds: ['emp-3', 'emp-4'],
    bayNumber: 'Bay 1 (Master Clean Room)',
    checkIn: {
      checkInDate: '2026-09-25T09:00:00Z',
      receivedByEmployeeId: 'emp-2',
      odometerReading: 6420,
      fuelLevel: 'THREE_QUARTERS',
      interiorCondition: 'CLEAN',
      glassCondition: 'GOOD',
      tyreCondition: 'GOOD',
      wheelCondition: 'CLEAN',
      personalBelongingsRemoved: true,
      preExistingDamages: [
        {
          id: 'dmg-1',
          panel: 'FRONT_BUMPER',
          damageType: 'PAINT_CHIP',
          severity: 'MINOR',
          description: 'Two tiny 1mm stone chips on lower carbon splitter lip.',
          photoUrl: '/images/hero-car.png',
        },
        {
          id: 'dmg-2',
          panel: 'HOOD',
          damageType: 'SWIRL_MARKS',
          severity: 'MODERATE',
          description: 'Swirl marks visible under 4000K LED inspection wand.',
          photoUrl: '/images/about-detailing.png',
        },
      ],
      checkInNotes: 'Vehicle brought in directly from track day. Carbon roof in flawless condition.',
    },
    customerComplaints: [
      'Paint looks slightly cloudy under direct sunlight after recent track session.',
      'Wants total protection against rock chips on front end and headlights.',
      'Brake dust buildup on wheels needs ceramic coating.',
    ],
    customerComplaintNotes: 'Client specifically requested 100% paint correction before applying PPF to lock in perfection.',
    inspectionFindings: [
      {
        id: 'fnd-1',
        area: 'Entire Body Paintwork',
        observation: 'Paint thickness averages 125-140 microns across panels. Clear coat is hard German clear coat. Moderate buffer trails from dealership.',
        recommendedServiceId: 'srv-paint-correction-3stage',
        recommendedServiceName: 'Multi-Stage Concours Paint Correction & Swirl Removal',
        priority: 'URGENT',
        estimatedPrice: 22000,
        notes: 'Required prior to PPF installation.',
      },
      {
        id: 'fnd-2',
        area: 'Front End High-Impact Zone',
        observation: 'Vulnerable front splitter and low aerodynamic profile prone to stone impacts at high speed.',
        recommendedServiceId: 'srv-ppf-front',
        recommendedServiceName: 'High-Impact Track Pack PPF',
        priority: 'URGENT',
        estimatedPrice: 65000,
      },
      {
        id: 'fnd-3',
        area: 'Wheels & Calipers',
        observation: 'PCCB yellow calipers have minor brake dust accumulation.',
        recommendedServiceId: 'srv-wheels-off-ceramic',
        recommendedServiceName: 'Wheels-Off Ceramic Coating & Brake Caliper Sealant',
        priority: 'RECOMMENDED',
        estimatedPrice: 16000,
      },
    ],
    services: [
      {
        id: 'jsrv-1',
        serviceId: 'srv-paint-correction-3stage',
        title: 'Multi-Stage Concours Paint Correction & Swirl Removal',
        category: 'PAINT_CORRECTION',
        quantity: 1,
        unitPrice: 22000,
        discount: 2000,
        taxRate: 18,
        totalPrice: 23600,
        estimatedDurationHours: 14,
        assignedTechnicianId: 'emp-3',
        status: 'COMPLETED',
        approvedByCustomer: true,
        notes: 'Step 3 jeweling completed. Gloss reading increased from 78 to 96 GU.',
      },
      {
        id: 'jsrv-2',
        serviceId: 'srv-ppf-front',
        title: 'High-Impact Track Pack PPF (Front Bumper, Hood, Fenders, Mirrors)',
        category: 'PPF',
        quantity: 1,
        unitPrice: 65000,
        discount: 5000,
        taxRate: 18,
        totalPrice: 70800,
        estimatedDurationHours: 16,
        assignedTechnicianId: 'emp-4',
        status: 'IN_PROGRESS',
        approvedByCustomer: true,
        notes: 'Hood and front fenders installed with wrapped edges. Bumper currently being tacked.',
      },
      {
        id: 'jsrv-3',
        serviceId: 'srv-wheels-off-ceramic',
        title: 'Wheels-Off Ceramic Coating & Brake Caliper Sealant',
        category: 'WHEELS',
        quantity: 1,
        unitPrice: 16000,
        discount: 1000,
        taxRate: 18,
        totalPrice: 17700,
        estimatedDurationHours: 6,
        assignedTechnicianId: 'emp-3',
        status: 'PENDING',
        approvedByCustomer: true,
        notes: 'Awaiting completion of PPF installation before wheel removal.',
      },
    ],
    materials: [
      {
        id: 'mat-1',
        productId: 'inv-2',
        productName: 'SunTek Ultra 60" Gloss TPU PPF Roll',
        category: 'PPF',
        quantity: 0.35,
        unit: 'Roll',
        unitCost: 68000,
        totalCost: 23800,
        supplier: 'Eastman Chemical Company',
      },
      {
        id: 'mat-2',
        productId: 'inv-3',
        productName: 'Koch-Chemie Heavy Cut H9.02',
        category: 'POLISH',
        quantity: 0.25,
        unit: 'Bottle',
        unitCost: 2400,
        totalCost: 600,
        supplier: 'Koch-Chemie GmbH',
      },
      {
        id: 'mat-3',
        productId: 'inv-5',
        productName: 'Gyeon Q2 Rim High-Temp Wheel Coating',
        category: 'COATING',
        quantity: 1,
        unit: 'Bottle',
        unitCost: 3100,
        totalCost: 3100,
        supplier: 'Gyeon Quartz Global',
      },
    ],
    photos: [
      {
        id: 'pht-1',
        url: '/images/hero-car.png',
        stage: 'BEFORE',
        caption: 'Vehicle intake condition in receiving bay under ambient lighting.',
        panel: 'FRONT_BUMPER',
        uploadedByEmployeeId: 'emp-2',
        uploadedAt: '2026-09-25T09:15:00Z',
      },
      {
        id: 'pht-2',
        url: '/images/about-detailing.png',
        stage: 'DURING',
        caption: 'Stage 2 polishing with Rupes DA on Shark Blue fender.',
        panel: 'LEFT_FENDER',
        uploadedByEmployeeId: 'emp-3',
        uploadedAt: '2026-09-25T14:30:00Z',
      },
      {
        id: 'pht-3',
        url: '/images/protection-film.png',
        stage: 'DURING',
        caption: 'SunTek Ultra TPU film alignment and edge wrapping on hood.',
        panel: 'HOOD',
        uploadedByEmployeeId: 'emp-4',
        uploadedAt: '2026-09-26T08:15:00Z',
      },
    ],
    estimatedCost: 103000,
    approvedCost: 95000,
    actualFinalCost: 112100,
    internalMaterialCost: 27500,
    totalDiscount: 8000,
    taxAmount: 17100,
    amountPaid: 50000,
    balanceDue: 62100,
    paymentStatus: 'PARTIALLY_PAID',
    payments: [
      {
        id: 'pmt-1',
        amount: 50000,
        paymentMethod: 'UPI',
        status: 'COMPLETED',
        transactionRef: 'UPI/20260925/99812401',
        receivedByEmployeeId: 'emp-6',
        paymentDate: '2026-09-25T09:45:00Z',
        notes: 'Advance deposit received upon job sign-off.',
      },
    ],
    approvalStatus: 'APPROVED',
    approvalDate: '2026-09-25T09:30:00Z',
    approvalNotes: 'Client approved estimate via WhatsApp link with full digital confirmation.',
    timeline: [
      {
        id: 'tl-1',
        timestamp: '2026-09-25T09:00:00Z',
        action: 'Vehicle Checked In',
        description: 'Porsche 911 GT3 received by Arman Khan. 6,420 km logged.',
        employeeId: 'emp-2',
        employeeName: 'Arman Khan',
        category: 'CHECK_IN',
      },
      {
        id: 'tl-2',
        timestamp: '2026-09-25T09:20:00Z',
        action: 'Digital Inspection Completed',
        description: '3 inspection findings recorded. Paint depth measured at 135μm.',
        employeeId: 'emp-1',
        employeeName: 'Vikram Malhotra',
        category: 'INSPECTION',
      },
      {
        id: 'tl-3',
        timestamp: '2026-09-25T09:30:00Z',
        action: 'Estimate Approved by Customer',
        description: 'Estimate of ₹95,000 + GST approved by Rohan Singhania.',
        employeeId: 'emp-2',
        employeeName: 'Arman Khan',
        category: 'APPROVAL',
      },
      {
        id: 'tl-4',
        timestamp: '2026-09-25T09:45:00Z',
        action: 'Advance Payment Received',
        description: '₹50,000 received via UPI (Ref: UPI/20260925/99812401).',
        employeeId: 'emp-6',
        employeeName: 'Ananya Verma',
        category: 'PAYMENT',
      },
      {
        id: 'tl-5',
        timestamp: '2026-09-25T11:00:00Z',
        action: 'Paint Correction Started',
        description: 'Multi-stage compounding and jeweling initiated by Master Rajesh Sharma.',
        employeeId: 'emp-3',
        employeeName: 'Rajesh Sharma',
        category: 'PROGRESS',
      },
      {
        id: 'tl-6',
        timestamp: '2026-09-25T18:00:00Z',
        action: 'Paint Correction Completed',
        description: 'Surface inspected under 3-spectrum lights. Zero holograms or haze.',
        employeeId: 'emp-3',
        employeeName: 'Rajesh Sharma',
        category: 'PROGRESS',
      },
      {
        id: 'tl-7',
        timestamp: '2026-09-26T08:00:00Z',
        action: 'PPF Application Started',
        description: 'Clean room sterilized. PPF pattern installation commenced on front end.',
        employeeId: 'emp-4',
        employeeName: 'Kabir Sengupta',
        category: 'PROGRESS',
      },
    ],
    createdAt: '2026-09-25T09:00:00Z',
    updatedAt: '2026-09-26T08:30:00Z',
    expectedDeliveryDate: '2026-09-27T17:00:00Z',
  },
  {
    id: 'job-102',
    jobCode: 'AZ-102',
    customerId: 'cust-102',
    vehicleId: 'veh-3',
    status: 'QUALITY_CHECK',
    priority: 'HIGH',
    assignedEmployeeId: 'emp-2',
    assignedTechnicianIds: ['emp-3', 'emp-5'],
    bayNumber: 'Bay 2 (Coating & Detailing)',
    checkIn: {
      checkInDate: '2026-09-24T10:30:00Z',
      receivedByEmployeeId: 'emp-2',
      odometerReading: 14250,
      fuelLevel: 'HALF',
      interiorCondition: 'MODERATE',
      glassCondition: 'GOOD',
      tyreCondition: 'GOOD',
      wheelCondition: 'CLEAN',
      personalBelongingsRemoved: true,
      preExistingDamages: [
        {
          id: 'dmg-3',
          panel: 'LEFT_FRONT_DOOR',
          damageType: 'SCRATCH',
          severity: 'MINOR',
          description: 'Faint 3cm surface clearcoat scratch near door handle.',
          photoUrl: '/images/cta-interior.png',
        },
      ],
      checkInNotes: 'Dr. Priya requested completely unscented interior care products.',
    },
    customerComplaints: [
      'Paint has lost hydrophobic shine after monsoon season.',
      'Silverstone leather seats have light blue denim dye transfer.',
    ],
    inspectionFindings: [
      {
        id: 'fnd-4',
        area: 'Exterior Paintwork',
        observation: 'Water spot mineral etching on roof and trunk lid. Clearcoat gloss measured at 81 GU.',
        recommendedServiceId: 'srv-ceramic-9h',
        recommendedServiceName: '9H Dual-Layer Matrix Ceramic Coating',
        priority: 'URGENT',
        estimatedPrice: 42000,
      },
      {
        id: 'fnd-5',
        area: 'Cabin Leather',
        observation: 'Driver seat bolster showing denim stain. Foam structure is intact.',
        recommendedServiceId: 'srv-interior-steam-spa',
        recommendedServiceName: 'Deep Interior Steam Sanitization & Leather Hydration',
        priority: 'URGENT',
        estimatedPrice: 12500,
      },
    ],
    services: [
      {
        id: 'jsrv-4',
        serviceId: 'srv-ceramic-9h',
        title: '9H Dual-Layer Matrix Ceramic Coating (5-Year Warranty)',
        category: 'CERAMIC',
        quantity: 1,
        unitPrice: 42000,
        discount: 2000,
        taxRate: 18,
        totalPrice: 47200,
        estimatedDurationHours: 18,
        assignedTechnicianId: 'emp-3',
        status: 'COMPLETED',
        approvedByCustomer: true,
        notes: 'Base 9H layer cured under IR heat lamps for 4 hours. Topcoat applied.',
      },
      {
        id: 'jsrv-5',
        serviceId: 'srv-interior-steam-spa',
        title: 'Deep Interior Steam Sanitization & Leather Hydration (Fragrance-Free)',
        category: 'INTERIOR',
        quantity: 1,
        unitPrice: 12500,
        discount: 500,
        taxRate: 18,
        totalPrice: 14160,
        estimatedDurationHours: 8,
        assignedTechnicianId: 'emp-5',
        status: 'COMPLETED',
        approvedByCustomer: true,
        notes: 'Leather dye removed safely with Koch-Chemie Pol Star. Matte balm applied.',
      },
    ],
    materials: [
      {
        id: 'mat-4',
        productId: 'inv-1',
        productName: 'Gyeon Q2 Syncro EVO Ceramic Coating Kit',
        category: 'COATING',
        quantity: 1,
        unit: 'Kit',
        unitCost: 8200,
        totalCost: 8200,
      },
      {
        id: 'mat-5',
        productId: 'inv-6',
        productName: 'Koch-Chemie Leather Star Conditioner',
        category: 'CLEANER',
        quantity: 0.3,
        unit: 'Bottle',
        unitCost: 1950,
        totalCost: 585,
      },
    ],
    photos: [
      {
        id: 'pht-4',
        url: '/images/ceramic-coating.png',
        stage: 'DURING',
        caption: 'Gyeon Syncro EVO coating application in cross-hatch pattern.',
        panel: 'HOOD',
        uploadedByEmployeeId: 'emp-3',
        uploadedAt: '2026-09-25T11:00:00Z',
      },
      {
        id: 'pht-5',
        url: '/images/steam-cleaning.png',
        stage: 'AFTER',
        caption: 'Silverstone leather restored to original matte factory finish.',
        panel: 'INTERIOR',
        uploadedByEmployeeId: 'emp-5',
        uploadedAt: '2026-09-25T16:00:00Z',
      },
    ],
    estimatedCost: 54500,
    approvedCost: 52000,
    actualFinalCost: 61360,
    internalMaterialCost: 8785,
    totalDiscount: 2500,
    taxAmount: 9360,
    amountPaid: 46360,
    balanceDue: 15000,
    paymentStatus: 'PARTIALLY_PAID',
    payments: [
      {
        id: 'pmt-2',
        amount: 46360,
        paymentMethod: 'CREDIT_CARD',
        status: 'COMPLETED',
        transactionRef: 'TXN-CC-882910',
        receivedByEmployeeId: 'emp-6',
        paymentDate: '2026-09-24T11:00:00Z',
      },
    ],
    approvalStatus: 'APPROVED',
    approvalDate: '2026-09-24T10:45:00Z',
    approvalNotes: 'Client confirmed via phone approval.',
    timeline: [
      {
        id: 'tl-8',
        timestamp: '2026-09-24T10:30:00Z',
        action: 'Vehicle Checked In',
        description: 'BMW M4 Competition received by Arman Khan.',
        employeeId: 'emp-2',
        employeeName: 'Arman Khan',
        category: 'CHECK_IN',
      },
      {
        id: 'tl-9',
        timestamp: '2026-09-25T17:30:00Z',
        action: 'Quality Inspection Audit',
        description: 'Vikram Malhotra conducting final IR curing check and panel audit.',
        employeeId: 'emp-1',
        employeeName: 'Vikram Malhotra',
        category: 'QUALITY',
      },
    ],
    createdAt: '2026-09-24T10:30:00Z',
    updatedAt: '2026-09-26T07:45:00Z',
    expectedDeliveryDate: '2026-09-26T15:00:00Z',
  },
  {
    id: 'job-103',
    jobCode: 'AZ-103',
    customerId: 'cust-103',
    vehicleId: 'veh-4',
    status: 'READY_FOR_DELIVERY',
    priority: 'NORMAL',
    assignedEmployeeId: 'emp-1',
    assignedTechnicianIds: ['emp-3', 'emp-4'],
    bayNumber: 'Bay 3 (Delivery Staging)',
    checkIn: {
      checkInDate: '2026-09-23T11:00:00Z',
      receivedByEmployeeId: 'emp-1',
      odometerReading: 9100,
      fuelLevel: 'FULL',
      interiorCondition: 'CLEAN',
      glassCondition: 'GOOD',
      tyreCondition: 'GOOD',
      wheelCondition: 'CLEAN',
      personalBelongingsRemoved: true,
      preExistingDamages: [],
      checkInNotes: 'Immaculate Nardo Grey RS6 Avant. Annual ceramic maintenance coat requested.',
    },
    customerComplaints: ['Annual 12-month ceramic coating maintenance inspection and topup.'],
    inspectionFindings: [
      {
        id: 'fnd-6',
        area: 'Ceramic Coating Health',
        observation: 'Hydrophobic performance at 85%. Slight traffic film on lower doors.',
        recommendedServiceId: 'srv-glass-ceramic',
        recommendedServiceName: 'Windshield & All-Glass Hydrophobic Ceramic Rain Repellent',
        priority: 'RECOMMENDED',
        estimatedPrice: 7500,
      },
    ],
    services: [
      {
        id: 'jsrv-6',
        serviceId: 'srv-glass-ceramic',
        title: 'Windshield & All-Glass Hydrophobic Ceramic Rain Repellent',
        category: 'CERAMIC',
        quantity: 1,
        unitPrice: 7500,
        discount: 500,
        taxRate: 18,
        totalPrice: 8260,
        estimatedDurationHours: 3,
        assignedTechnicianId: 'emp-3',
        status: 'COMPLETED',
        approvedByCustomer: true,
      },
    ],
    materials: [
      {
        id: 'mat-6',
        productId: 'inv-7',
        productName: 'Edgeless Korean 500GSM Microfiber Pack',
        category: 'CONSUMABLE',
        quantity: 1,
        unit: 'Pack',
        unitCost: 1400,
        totalCost: 1400,
      },
    ],
    photos: [
      {
        id: 'pht-6',
        url: '/images/rims-tires.png',
        stage: 'AFTER',
        caption: 'Final walkaround reflection and gloss inspection complete.',
        panel: 'WHEELS',
        uploadedByEmployeeId: 'emp-1',
        uploadedAt: '2026-09-25T18:00:00Z',
      },
    ],
    estimatedCost: 7500,
    approvedCost: 7000,
    actualFinalCost: 8260,
    internalMaterialCost: 1400,
    totalDiscount: 500,
    taxAmount: 1260,
    amountPaid: 8260,
    balanceDue: 0,
    paymentStatus: 'PAID',
    payments: [
      {
        id: 'pmt-3',
        amount: 8260,
        paymentMethod: 'CREDIT_CARD',
        status: 'COMPLETED',
        transactionRef: 'CC-RS6-9901',
        receivedByEmployeeId: 'emp-6',
        paymentDate: '2026-09-25T18:15:00Z',
      },
    ],
    approvalStatus: 'APPROVED',
    approvalDate: '2026-09-23T11:30:00Z',
    timeline: [
      {
        id: 'tl-10',
        timestamp: '2026-09-23T11:00:00Z',
        action: 'Vehicle Checked In',
        description: 'Audi RS 6 Avant received by Vikram Malhotra.',
        employeeId: 'emp-1',
        employeeName: 'Vikram Malhotra',
        category: 'CHECK_IN',
      },
      {
        id: 'tl-11',
        timestamp: '2026-09-25T18:30:00Z',
        action: 'Ready For Delivery',
        description: 'Passed 48-point quality checklist. Staged in clean delivery bay.',
        employeeId: 'emp-1',
        employeeName: 'Vikram Malhotra',
        category: 'QUALITY',
      },
    ],
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-25T18:30:00Z',
    expectedDeliveryDate: '2026-09-26T11:00:00Z',
  },
  {
    id: 'job-104',
    jobCode: 'AZ-104',
    customerId: 'cust-104',
    vehicleId: 'veh-5',
    status: 'INSPECTION',
    priority: 'HIGH',
    assignedEmployeeId: 'emp-2',
    assignedTechnicianIds: ['emp-5'],
    bayNumber: 'Bay 4 (Wash & Decon)',
    checkIn: {
      checkInDate: '2026-09-26T08:15:00Z',
      receivedByEmployeeId: 'emp-2',
      odometerReading: 23400,
      fuelLevel: 'QUARTER',
      interiorCondition: 'HEAVILY_SOILED',
      glassCondition: 'GOOD',
      tyreCondition: 'WORN',
      wheelCondition: 'CURBED',
      personalBelongingsRemoved: false,
      preExistingDamages: [
        {
          id: 'dmg-4',
          panel: 'RIGHT_REAR_DOOR',
          damageType: 'DENT',
          severity: 'MODERATE',
          description: 'Door ding dent near lower rock slider from off-road trail.',
          photoUrl: '/images/hero-car.png',
        },
      ],
      checkInNotes: 'Vehicle returned from Ladakh expedition. Heavy silt and sand throughout chassis.',
    },
    customerComplaints: [
      'Complete interior and underbody deep sanitization.',
      'Paint has trail bush pinstripe scratches.',
    ],
    inspectionFindings: [
      {
        id: 'fnd-7',
        area: 'Engine Bay & Undercarriage',
        observation: 'Radiator fins filled with dried clay. Requires delicate low-pressure steam degreasing.',
        recommendedServiceId: 'srv-engine-bay-detail',
        recommendedServiceName: 'Engine Bay Steam Cleaning & Satin Dressing',
        priority: 'URGENT',
        estimatedPrice: 6500,
      },
      {
        id: 'fnd-8',
        area: 'Exterior Clearcoat',
        observation: 'Clearcoat micro-scratches along both flank doors from vegetation.',
        recommendedServiceId: 'srv-paint-correction-3stage',
        recommendedServiceName: 'Multi-Stage Concours Paint Correction & Swirl Removal',
        priority: 'RECOMMENDED',
        estimatedPrice: 22000,
      },
    ],
    services: [],
    materials: [],
    photos: [],
    estimatedCost: 28500,
    approvedCost: 0,
    actualFinalCost: 0,
    internalMaterialCost: 0,
    totalDiscount: 0,
    taxAmount: 0,
    amountPaid: 0,
    balanceDue: 0,
    paymentStatus: 'UNPAID',
    payments: [],
    approvalStatus: 'DRAFT',
    timeline: [
      {
        id: 'tl-12',
        timestamp: '2026-09-26T08:15:00Z',
        action: 'Vehicle Checked In',
        description: 'Land Rover Defender 110 received by Arman Khan.',
        employeeId: 'emp-2',
        employeeName: 'Arman Khan',
        category: 'CHECK_IN',
      },
      {
        id: 'tl-13',
        timestamp: '2026-09-26T08:45:00Z',
        action: 'Underbody Inspection In Progress',
        description: 'Siddharth Rao inspecting clay buildup and suspension bushings.',
        employeeId: 'emp-5',
        employeeName: 'Siddharth Rao',
        category: 'INSPECTION',
      },
    ],
    createdAt: '2026-09-26T08:15:00Z',
    updatedAt: '2026-09-26T08:45:00Z',
    expectedDeliveryDate: '2026-09-28T18:00:00Z',
  },
]
